chore: refactor secrets to use environment secrets

diff --git a/.github/workflows/terraform-v2-plan.yml b/.github/workflows/terraform-v2-plan.yml
--- a/.github/workflows/terraform-v2-plan.yml
+++ b/.github/workflows/terraform-v2-plan.yml
@@ -6,36 +6,43 @@ on:
       environment:
         description: env to deploy
         type: choice
-        options: [DEV, TEST, PROD]
-        default: DEV
+        options: [dev, test, prod]
+        default: dev
+      staging-env:
+        description: production vs sandbox evironment
+        type: choice
+        options: [sandbox, production]
+        default: sandbox
+
 env:
   TF_VERSION: 1.11.0
 
 jobs:
   terraform:
     runs-on: ubuntu-24.04
+    environment:
+      name: ${{inputs.staging-env}}-${{ inputs.environment }}
+      deployment: false
     timeout-minutes: 30
     permissions:
       contents: read
       id-token: write
     steps:
     - uses: hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820 #v2
-    - name: Fail if not main or dev
-      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'
-      run: |
-        echo "This workflow only runs on main or dev branches."
-        exit 1
+
+    # for now  allow for all branches
+    # - name: Fail if not main or dev
+    #   if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'
+    #   run: |
+    #     echo "This workflow only runs on main or dev branches."
+    #     exit 1
 
     - name: Set common variables
-      run: |
-        echo "DEV_AZUREIDIR_TENANT_ID=${{ secrets.DEV_AZUREIDIR_TENANT_ID }}" >> $GITHUB_ENV
-        echo "TEST_AZUREIDIR_TENANT_ID=${{ secrets.TEST_AZUREIDIR_TENANT_ID }}" >> $GITHUB_ENV
-        echo "PROD_AZUREIDIR_TENANT_ID=${{ secrets.PROD_AZUREIDIR_TENANT_ID }}" >> $GITHUB_ENV
-        echo "LOWER_ENV=$(echo "${{ inputs.environment }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
+      run: echo "UPPER_ENV=$(echo "${{ inputs.environment }}" | tr '[:lower:]' '[:upper:]')" >> $GITHUB_ENV
 
     # TO BE REFACTORED WHEN THE SECRETS ARE MOVED TO OPENSHIFT
     - name: Set dev branch environment to SANDBOX
-      if: github.ref == 'refs/heads/dev'
+      if: ${{inputs.staging-env}} == 'sandbox'  # && github.ref == 'refs/heads/dev'
       run: |
         echo "KEYCLOAK_V2_DEV_URL=https://dev.sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
         echo "KEYCLOAK_V2_TEST_URL=https://test.sandbox.loginproxy.gov.bc.ca" >> $GITHUB_ENV
@@ -79,7 +86,7 @@ jobs:
         # PROJECT_SUFFIX left null for production config
 
     - name: Set main branch environment to PRODUCTION
-      if: github.ref == 'refs/heads/main'
+      if: ${{inputs.staging-env}} == 'production'  # && github.ref == 'refs/heads/main'
       run: |
         echo "KEYCLOAK_V2_DEV_URL=https://dev.loginproxy.gov.bc.ca" >> $GITHUB_ENV
         echo "KEYCLOAK_V2_TEST_URL=https://test.loginproxy.gov.bc.ca" >> $GITHUB_ENV
@@ -100,26 +107,26 @@ jobs:
     - name: Setup Terraform
       uses: ./.github/actions/setup-terraform
       with:
-        context: ./terraform-v2/keycloak-${{ env.LOWER_ENV }}
+        context: ./terraform-v2/keycloak-${{inputs.environment}}
         tf-version: ${{ env.TF_VERSION }}
         tf-s3-bucket: ${{ env.TF_S3_BUCKET }}
         tf-s3-bucket-key: keycloak/gold-${{ inputs.environment }}
-        tf-aws-deploy-role-arn: ${{ secrets[format('SSO_AWS_GH_ACTIONS_DEPLOYER{0}', env.PROJECT_SUFFIX)] }}
+        tf-aws-deploy-role-arn: ${{ secrets.SSO_AWS_GH_ACTIONS_DEPLOYER }}
         kc-provider-version: 5.4.0
-        kc-url: ${{ env[format('KEYCLOAK_V2_{0}_URL', inputs.environment)] }}
-        kc-username: ${{ secrets[format('KEYCLOAK_V2_{0}_USERNAME{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        kc-password: ${{ secrets[format('KEYCLOAK_V2_{0}_PASSWORD{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        azureidir-tenant-id: ${{ env[format('{0}_AZUREIDIR_TENANT_ID', inputs.environment)] }}
-        azureidir-client-id: ${{ secrets[format('{0}_AZUREIDIR_CLIENT_ID{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        azureidir-client-secret: ${{ secrets[format('{0}_AZUREIDIR_CLIENT_SECRET{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        github-client-id: ${{ secrets[format('{0}_GITHUB_CLIENT_ID{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        github-client-secret: ${{ secrets[format('{0}_GITHUB_CLIENT_SECRET{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        digitalcredential-client-id: ${{ secrets[format('{0}_DIGITALCREDENTIAL_CLIENT_ID{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        digitalcredential-client-secret: ${{ secrets[format('{0}_DIGITALCREDENTIAL_CLIENT_SECRET{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        otp-client-id: ${{ secrets[format('{0}_OTP_CLIENT_ID{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        otp-client-secret: ${{ secrets[format('{0}_OTP_CLIENT_SECRET{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        ppid-client-id: ${{ secrets[format('{0}_PPID_CLIENT_ID{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
-        ppid-client-secret: ${{ secrets[format('{0}_PPID_CLIENT_SECRET{1}', inputs.environment, env.PROJECT_SUFFIX)] }}
+        kc-url: ${{ env[format('KEYCLOAK_V2_{0}_URL', env.UPPER_ENV )] }}
+        kc-username: ${{ secrets.KEYCLOAK_V2_USERNAME }}
+        kc-password: ${{ secrets.KEYCLOAK_V2_PASSWORD }}
+        azureidir-tenant-id: ${{ secrets.AZUREIDIR_TENANT_ID }}
+        azureidir-client-id: ${{ secrets.AZUREIDIR_CLIENT_ID }}
+        azureidir-client-secret: ${{ secrets.AZUREIDIR_CLIENT_SECRET }}
+        github-client-id: ${{ secrets.GITHUB_CLIENT_ID }}
+        github-client-secret: ${{ secrets.GITHUB_CLIENT_SECRET }}
+        digitalcredential-client-id: ${{ secrets.DIGITALCREDENTIAL_CLIENT_ID }}
+        digitalcredential-client-secret: ${{ secrets.DIGITALCREDENTIAL_CLIENT_SECRET }}
+        otp-client-id: ${{ secrets.OTP_CLIENT_ID}}
+        otp-client-secret: ${{ secrets.OTP_CLIENT_SECRET }}
+        ppid-client-id: ${{ secrets.PPID_CLIENT_ID }}
+        ppid-client-secret: ${{ secrets.PPID_CLIENT_SECRET }}
         #prod for prod-Production, test for sandbox and dev-Production and test-Production
         siteminder-signing-certificate: ${{ secrets[format('{0}_SITEMINDER_SIGNING_CERTIFICATE', env.SITEMINDER_PROJECT)] }}
 
